import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About/About'
import Banner from '../components/Banner/Banner'
import Navbar from '../components/Navbar/Navbar'
import OurWork from '../components/OurWork/OurWork'
import Services from '../components/Services/Services'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Glitch Cloud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Banner />
      <OurWork />
      <Services />
      <About />
    </div>
  )
}
